apiVersion: apps/v1
kind: Deployment
metadata:
  name: component-2-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: component-2-2
  template:
    metadata:
      labels:
        app: component-2-2
    spec:
      containers:
      - name: component-2-2
        image: component-2-2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://104.196.114.221:27017/calificaciones_db"
        - name: SPRING_GRAPHQL_SCHEMA_LOCATION
          value: "classpath:/graphql/"
