apiVersion: v1
kind: Service
metadata:
  name: nginx-balancer
spec:
  type: LoadBalancer
  selector:
    app: nginx-balancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
