apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s-manifests/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: component-4
  name: component-4
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: component-4
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s-manifests/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: component-4
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: 34.51.32.217
            - name: DB_NAME
              value: authdb
            - name: DB_PASSWORD
              value: postgres123
            - name: DB_PORT
              value: "5432"
            - name: DB_SSL_MODE
              value: disable
            - name: DB_USER
              value: postgres
            - name: FrontendURL
              value: https://nginx-balancer
            - name: GOOGLE_CLIENT_ID
              value: '"97072811302-e0foheebjj6kto3k8efabljk2t453vbe.apps.googleusercontent.com"'
            - name: GOOGLE_CLIENT_SECRET
              value: '"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"'
            - name: GOOGLE_REDIRECT_URL
              value: https://nginx-balancer/auth/callback
            - name: JWT_EXPIRATION
              value: "3600"
            - name: JWT_SECRET
              value: '"nbu8dTVEoJ/1pnIaOj+JM+Jrui/jLvtIKmXgGScb1ndzEfBb4GbqIz45gcMdRmb4ptfBNA1+/sCtttvpZPL8Vg"'
            - name: PORT
              value: "8082"
          image: northamerica-south1-docker.pkg.dev/gradex-swarch/gradex-repo/gx_be_auth:latest
          name: gx-be-auth
          ports:
            - containerPort: 8082
              protocol: TCP
      restartPolicy: Always
