apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s-manifests/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: gx-fe-gradex-3
  name: gx-fe-gradex-3
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: gx-fe-gradex-3
