apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s-manifests/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: nginx-proxy
  name: nginx-proxy
spec:
  type: LoadBalancer
  ports:
    - name: "444"
      port: 444
      targetPort: 443
  selector:
    io.kompose.service: nginx-proxy
